import {describe,it,expect} from 'vitest';
import {program,defaults,createSession,completeSession,nextPosition,targets,validSet,ordered,progress} from '../src/model';
describe('workbook import and workout behavior',()=>{
 it('contains all nine weeks and the exact six-session sequence',()=>{expect(program).toHaveLength(54);for(let w=0;w<9;w++){expect(program.slice(w*6,w*6+6).map(s=>s.name)).toEqual(['Lower #1','Upper #1','Lower #2','Upper #2','Lower #3','Upper #3']);expect(program.slice(w*6,w*6+6).every(s=>s.week===w+1)).toBe(true);}expect(program.flatMap(s=>s.exercises)).toHaveLength(360);});
 it('preserves week-to-week changes rather than repeating week one',()=>{expect(program[0].exercises[0].reps).toBe('4');expect(program[6].exercises[0].reps).toBe('5');expect(program[12].exercises[0].reps).toBe('6');expect(program[36].exercises.map(e=>e.name)).not.toEqual(program[0].exercises.map(e=>e.name));});
 it('starts with no imported weights or completion flags',()=>{const s=createSession(defaults,[]);expect(s.exercises[0].sets[0].segments[0].weight).toBeNull();expect(progress(s).done).toBe(0);expect(s.finishedAt).toBeNull();});
 it('gives separate starts unique identifiers even in the same program slot',()=>{const a=createSession(defaults,[],new Date(2026,8,23)),b=createSession(defaults,[],new Date(2026,8,25));expect(a.id).not.toBe(b.id);expect(a.index).toBe(b.index);});
 it('separates a segmented prescription and handles timed/AMRAP sets',()=>{expect(targets(program[0].exercises[4])).toEqual([6,6]);expect(targets(program[3].exercises[4])).toEqual([7,7,7]);expect(targets(program[5].exercises[1])).toEqual([null,2]);expect(targets(program[40].exercises.find(e=>e.name==='Plank')!)).toEqual([30]);});
 it('requires actual weight and reps before completion',()=>{const s=createSession(defaults,[]),e=s.exercises[0];expect(validSet(e.sets[0],e.exercise)).toBe(false);e.sets[0].segments[0].weight=45;expect(validSet(e.sets[0],e.exercise)).toBe(true);e.sets[0].segments[0].reps=null;expect(validSet(e.sets[0],e.exercise)).toBe(false);});
 it('marks unfinished sets skipped and advances one slot',()=>{const s=createSession(defaults,[]);s.exercises[0].sets[0].done=true;const result=completeSession(s);expect(result.exercises[0].sets[0].skipped).toBe(false);expect(result.exercises[0].sets[1].skipped).toBe(true);expect(nextPosition(result)).toEqual({position:1,cycle:1});});
 it('loops after week nine and preserves cycle identity',()=>{const s=createSession({...defaults,position:53,cycle:2},[]);expect(nextPosition(s)).toEqual({position:0,cycle:3});});
 it('reuses previous actual weight and reps but resets completion',()=>{const s=createSession(defaults,[]);s.exercises[0].sets[0].segments[0].weight=50;s.exercises[0].sets[0].done=true;const history=[completeSession(s)];const next=createSession({...defaults,position:6},history);expect(next.exercises[0].sets[0].segments[0]).toEqual({weight:50,reps:4});expect(next.exercises[0].exercise.reps).toBe('5');expect(next.exercises[0].sets[0].done).toBe(false);});
 it('does not reuse weights after unit or exercise changes',()=>{const s=createSession(defaults,[]);s.exercises[0].sets[0].segments[0].weight=50;const e=s.exercises[0].exercise;const next=createSession({...defaults,overrides:{[e.id]:{unit:'kg'}}},[completeSession(s)]);expect(next.exercises[0].sets[0].segments[0].weight).toBeNull();});
 it('removes zero-set exercises and follows configured order',()=>{const t=program[0],ids=t.exercises.map(e=>e.id).reverse();const settings={...defaults,orders:{[t.id]:ids},overrides:{[ids[0]]:{sets:0}}};expect(ordered(t,settings).map(e=>e.id)).toEqual(ids.slice(1));});
});
